controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_index:
    path: /api
    controller: App\Controller\ApiController::index
    methods: GET

api_user:
    resource: '../src/Controller/UserController.php'
    type: annotation